-- Cloudflare D1 Database Schema for Optimo Prompt Ai
-- User management and subscription tracking

CREATE TABLE users (
    user_id TEXT PRIMARY KEY,                       -- Unique ID generated by the extension install
    llm_api_key_encrypted TEXT,                     -- User's LLM API key, encrypted
    subscription_status TEXT NOT NULL DEFAULT 'freemium', -- 'freemium', 'premium'
    paddle_subscription_id TEXT,                    -- The subscription ID from Paddle
    paddle_customer_id TEXT,                        -- The customer ID from Paddle
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for efficient lookups
CREATE INDEX idx_paddle_subscription_id ON users (paddle_subscription_id);
CREATE INDEX idx_paddle_customer_id ON users (paddle_customer_id);

-- Create usage tracking table for optimization counts
CREATE TABLE usage_tracking (
    user_id TEXT,
    optimization_date DATE,
    optimization_count INTEGER DEFAULT 0,
    PRIMARY KEY (user_id, optimization_date),
    FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- Create optimization history table
CREATE TABLE optimization_history (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT,
    original_prompt TEXT,
    optimized_prompt TEXT,
    optimization_settings TEXT, -- JSON string of tone, length, persona, audience
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- Create saved prompts library table
CREATE TABLE saved_prompts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT,
    title TEXT,
    content TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users (user_id)
);

-- Indexes for performance
CREATE INDEX idx_usage_date ON usage_tracking (optimization_date);
CREATE INDEX idx_history_user ON optimization_history (user_id);
CREATE INDEX idx_saved_prompts_user ON saved_prompts (user_id);